### ISSUE TITLE
aftership-sdk 2.0.7版本调用POST请求所有方法报错

### ISSUE THREAD

**Issue by lchuai2018** [AfterShip/aftership-sdk-java#17]
requestBody = RequestBody.create(JsonUtils.getGson().toJson(requestData), JSON); 参数值写返了，导致POST请求报错
报错信息详情如下：
okhttp3.RequestBody.create(Ljava/lang/String;Lokhttp3/MediaType;)Lokhttp3/RequestBody;

**Comment by Bossa573** [comment]
Hello @lchuai2018 , please verify the latest version 2.0.8, 
feel free to reopen the issue if the bug still exists.

**Comment by linsiming** [comment]
> Hello @lchuai2018 , please verify the latest version 2.0.8,
> feel free to reopen the issue if the bug still exists.

Hi, the bug still exists. @Bossa573

**Comment by Bossa573** [comment]
@linsiming can you post the code snippet to reproduce the issue?

**Comment by linsiming** [comment]
> @linsiming can you post the code snippet to reproduce the issue?

Yes.
The example I'm using is "aftership-sample/src/main/java/com/aftership/sample/tracking/CreateTrackingSample.java"


java.lang.NoSuchMethodError: okhttp3.RequestBody.create(Ljava/lang/String;Lokhttp3/MediaType;)Lokhttp3/RequestBody;

	at com.aftership.sdk.request.ApiRequestImpl.makeRequest(ApiRequestImpl.java:92)
	at com.aftership.sdk.endpoint.impl.TrackingImpl.createTracking(TrackingImpl.java:42)
	at com.wezone.demo.test.aftership.TrackingApiTest.testCreateTracking(TrackingApiTest.java:137)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:221)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
