### ISSUE TITLE
API response unsuccessful throw IlleagalStateException

### ISSUE THREAD

**Issue by DearWhite** [AfterShip/aftership-sdk-java#20]
aftership-sdk 2.0.7版本：API response unsuccessful throw IlleagalStateException
Caused by: java.lang.IllegalStateException: closed
	at okio.RealBufferedSource.select(RealBufferedSource.kt:220)
	at okhttp3.internal.Util.readBomAsCharset(Util.kt:259)
	at okhttp3.ResponseBody.string(ResponseBody.kt:187)
	at com.aftership.sdk.request.ApiRequestImpl.entryResponseBody(ApiRequestImpl.java:238)
	at com.aftership.sdk.request.ApiRequestImpl.makeRequest(ApiRequestImpl.java:113)

**Comment by xugenfa** [comment]
we have released v2.0.8 to fix it.

**Comment by Bossa573** [comment]
Hello @DearWhite , please verify the latest version 2.0.8, 
feel free to reopen the issue if the bug still exists.
