### ISSUE TITLE
Android Release build issue

### ISSUE THREAD

**Issue by andreii-sp** [AfterShip/aftership-sdk-java#23]
Lib version: `"com.aftership:aftership-sdk:2.0.8"`

Works fine when testing the app in `debug` but not able to make it work in `release` build.

**Comment by Bossa573** [comment]
@andreii-sp could you provide more detail about what errors you found?

**Comment by andreii-sp** [comment]
These are the logs that come up:

`E/c0: d.b.a.c.d: null; type: HandlerError; DEBUG_DATA::requestData:CourierDetectRequest(tracking=CourierDetectTracking(trackingNumber=7186640565, trackingPostalCode=null, trackingShipDate=null, trackingAccountNumber=null, trackingKey=null, trackingDestinationCountry=null, slug=null)); DEBUG_DATA::requestConfig: {path=/couriers/detect, method=POST}; 
DEBUG_DATA::requestHeaders: {aftership-api-key=54041021-f9a5-4b26-88fe-c8fcec74a111, request-id=b41df26e-3623-4417-8a2c-a398adebb6d2,
 Content-Type=application/json, aftership-agent=java-sdk-2.0.0}
        at d.b.a.e.b.a(ApiRequestImpl.java:57)
        at d.b.a.b.c.a.a(CourierImpl.java:4)
        at com.sightplan.sightplanlib.util.c0.h(PackageCodeValidator.java:4)
        at com.sightplan.sightplanlib.util.c0.i(PackageCodeValidator.java:1)
        at com.sightplan.sightplanlib.util.c.call(Unknown Source:4)
        at f.c.i0.e.f.h.t(SingleFromCallable.java:4)
        at f.c.y.a(Single.java:4)
        at f.c.i0.e.f.l$a.run(SingleSubscribeOn.java:1)
        at f.c.x$a.run(Scheduler.java:2)
        at f.c.i0.g.m.run(ScheduledRunnable.java:2)
        at f.c.i0.g.m.call(ScheduledRunnable.java:1)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)`
     
     Caused by: java.net.UnknownHostException: Unable to resolve host "api.aftership.com": No address associated with hostname
        at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:156)
        at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
        at java.net.InetAddress.getAllByName(InetAddress.java:1152)
        at h.s.lookup(Dns.kt:1)
        at h.k0.f.k.f(RouteSelector.kt:15)
        at h.k0.f.k.e(RouteSelector.kt:3)
        at h.k0.f.k.d(RouteSelector.kt:4)
        at h.k0.f.d.b(ExchangeFinder.kt:27)
        at h.k0.f.d.c(ExchangeFinder.kt:1)
        at h.k0.f.d.a(ExchangeFinder.kt:7)
        at h.k0.f.e.s(RealCall.kt:8)
        at h.k0.f.a.intercept(ConnectInterceptor.kt:2)
        at h.k0.g.g.a(RealInterceptorChain.kt:12)
        at h.k0.d.a.intercept(CacheInterceptor.kt:26)
        at h.k0.g.g.a(RealInterceptorChain.kt:12)
        at h.k0.g.a.intercept(BridgeInterceptor.kt:22)
        at h.k0.g.g.a(RealInterceptorChain.kt:12)
        at h.k0.g.j.intercept(RetryAndFollowUpInterceptor.kt:7)
        at h.k0.g.g.a(RealInterceptorChain.kt:12)
        at h.k0.f.e.r(RealCall.kt:16)
        at h.k0.f.e.execute(RealCall.kt:5)
        at d.b.a.e.b.a(ApiRequestImpl.java:12)
        at d.b.a.b.c.a.a(CourierImpl.java:4) 
        at com.sightplan.sightplanlib.util.c0.h(PackageCodeValidator.java:4) 
        at com.sightplan.sightplanlib.util.c0.i(PackageCodeValidator.java:1) 
        at com.sightplan.sightplanlib.util.c.call(Unknown Source:4) 
        at f.c.i0.e.f.h.t(SingleFromCallable.java:4) 
        at f.c.y.a(Single.java:4) 
        at f.c.i0.e.f.l$a.run(SingleSubscribeOn.java:1) 
        at f.c.x$a.run(Scheduler.java:2) 
        at f.c.i0.g.m.run(ScheduledRunnable.java:2) 
        at f.c.i0.g.m.call(ScheduledRunnable.java:1) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
       
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 
        
     Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
        at libcore.io.Linux.android_getaddrinfo(Native Method)
        at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:74)
        at libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:200)
        at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:74)
        at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:135)
        at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103) 
        at java.net.InetAddress.getAllByName(InetAddress.java:1152) 
        at h.s.lookup(Dns.kt:1) 
        at h.k0.f.k.f(RouteSelector.kt:15) 
        at h.k0.f.k.e(RouteSelector.kt:3) 
        at h.k0.f.k.d(RouteSelector.kt:4) 
        at h.k0.f.d.b(ExchangeFinder.kt:27) 
        at h.k0.f.d.c(ExchangeFinder.kt:1) 
        at h.k0.f.d.a(ExchangeFinder.kt:7) 
        at h.k0.f.e.s(RealCall.kt:8) 
        at h.k0.f.a.intercept(ConnectInterceptor.kt:2) 
        at h.k0.g.g.a(RealInterceptorChain.kt:12) 
        at h.k0.d.a.intercept(CacheInterceptor.kt:26) 
        at h.k0.g.g.a(RealInterceptorChain.kt:12) 
        at h.k0.g.a.intercept(BridgeInterceptor.kt:22) 
        at h.k0.g.g.a(RealInterceptorChain.kt:12) 
        at h.k0.g.j.intercept(RetryAndFollowUpInterceptor.kt:7) 
        at h.k0.g.g.a(RealInterceptorChain.kt:12) 
        at h.k0.f.e.r(RealCall.kt:16) 
        at h.k0.f.e.execute(RealCall.kt:5) 
        at d.b.a.e.b.a(ApiRequestImpl.java:12) 
        at d.b.a.b.c.a.a(CourierImpl.java:4) 
        at com.sightplan.sightplanlib.util.c0.h(PackageCodeValidator.java:4) 
        at com.sightplan.sightplanlib.util.c0.i(PackageCodeValidator.java:1) 
        at com.sightplan.sightplanlib.util.c.call(Unknown Source:4) 
        at f.c.i0.e.f.h.t(SingleFromCallable.java:4) 
        at f.c.y.a(Single.java:4) 
        at f.c.i0.e.f.l$a.run(SingleSubscribeOn.java:1) 
        at f.c.x$a.run(Scheduler.java:2) 
        at f.c.i0.g.m.run(ScheduledRunnable.java:2) 
        at f.c.i0.g.m.call(ScheduledRunnable.java:1) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        
        at 
        java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) `

**Comment by Bossa573** [comment]
from the log `java.net.UnknownHostException: Unable to resolve host "api.aftership.com"`

can you host connect to https://api.aftership.com ?

**Comment by andreii-sp** [comment]
@Bossa573 It seems I am able from my laptop browser but not from my emulated device browser

**Comment by andreii-sp** [comment]
From what I see the SSL trusted certificate set on your api page `Sectigo RSA Domain Validation Secure Server CA` is not present in the Android OS Trusted certificates list. I assume this might be a reason why I'm not able to access the page from my device.

**Comment by Bossa573** [comment]
since it's connectivity issue and irrelated to the java SDK itself, i will close the ticket first, feel free to reopen if there's any new findings
